[nginx]
nginx1  ansible_host=nginx1.ru-central1.internal
nginx2  ansible_host=nginx2.ru-central1.internal 

[zabbix]
zabbix  ansible_host=zabbix.ru-central1.internal

[elastic]
elastic ansible_host=elasticsearch.ru-central1.internal

[kibana]
kibana ansible_host=kibana.ru-central1.internal

[bastion]
bastion ansible_host=158.160.154.197 

[project:children]
nginx
zabbix
elastic
kibana
bastion

[project:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -q user@158.160.154.197 -i /home/user/.ssh/yc_ed25519 -W %h:%p"'


[all:vars]
ansible_connection='ssh'
ansible_ssh_port='22'
ansible_ssh_user='user'
ansible_ssh_private_key_file='/home/user/.ssh/yc_ed25519'
